import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'hr_HR': {
          "OpcijePrilagodbi": "Opcije prilagodbi",
          "BokJaSam": "Bok, ja sam",
          "Gibalica": "Gibalica",
          "BrojPonavljanjaVježbe": "Broj ponavljanja vježbe",
          "GibalicaGleda": "Gibalica gleda?",
          "Mene": "MENE",
          "Kartice": "KARTICE",
          "Igraj": "IGRAJ",
          "Trening": "TRENING",
          "GornjiDioTijela": "Gornji dio tijela",
          "DonjiDioTijela": "Donji dio tijela",
          "Sve": "Sve",
          "LijevaRuka": "Lijeva ruka",
          "DesnaRuka": "Desna ruka",
          "LijevaIDesnaRuka": "Lijeva i desna ruka",
          "Noge": "Noge",
          "NogeIČučanj": "Noge i čučanj",
          "KažeBok": "kaže bok!",
          "DragoMiTeVidjetiOvdje": "Veselim se našem druženju",
          "DobroDošaola": "kroz vježbu",
          "Kreni": "Kreni!",
          "Postavke": "POSTAVKE",
          "IspisKartica": "Ispis kartica",
          "PromjenaIzgledaAplikacije": "Promjena izgleda aplikacije",
          "SvijetliNačin": "Svijetli način",
          "TamniNačin": "Tamni način",
          "PromjenaVeličineTeksta": "Promjena veličine teksta",
          "Zvuk": "Zvuk",
          "UpaliZvuk": "Uključi",
          "UgasiZvuk": "Isključi",
          "PromjenaJezika": "Promjena jezika",
          "Hrvatski": "Hrvatski",
          "Engleski": "Engleski",
          "InformacijeOAplikaciji": "Informacije o aplikaciji",
          "PonovnoUpoznajAplikaciju": "Ponovno upoznaj aplikaciju",
          "Oooops": "Oooops... :(",
          "KakoBiNastaviolaDaljePotrebnoJeZadovoljitiSljedećeUvjete": "Kako bi nastavio/la dalje potrebno je zadovoljiti sljedeće uvjete:",
          "UpisatiSvojeIme": " - upisati svoje ime",
          "OdabratiAvatar": " - odabrati avatar",
          "OdabratiBaremJednuVježbu": " - odabrati barem jednu vježbu",
          "Osobno": "OSOBNO",
          "Ponavljanje": "Ponavljanje",
          "PONAVLJANJE1": "PONAVLJANJE",
          "DesnaNoga": "Desna noga",
          "LijevaNoga": "Lijeva noga",
          "KlikniZaViše": "Klikni za više!",
          "PodatciOVježbanju": "Podatci o vježbanju",
          "Preskoči": "Preskoči",
          "UpoznajmoSe": "Upoznajmo se!",
          "SadaKadaZnašŠtoTeSveČekaMožemoKrenuti": "Sada kada znaš što te sve čeka, možemo krenuti",
          "DanINoć": "DAN i NOĆ",
          "GibajSe": "Gibaj se!",
          "SuperSadaJeSveSpremno": "Super, sada je sve spremno!",
          "LijevaUVis": "Lijeva u vis",
          "DesnaUVis": "Desna u vis",
          "SaStrane": "Sa strane",
          "UVisISaStrane": "U vis i sa strane",
          "RukeI": "RUKE i",
          "Obje": "OBJE",
          "LijevaIliDesnaUVis": "Lijeva ili desna u vis",
          "Raskorak": "Raskorak",
          "UVisISaStraneIstiPoložaj": "U vis i sa strane isti položaj",
          "UVisISaStraneRazičitiPoložaj": "U vis i sa strane razičiti položaj",
          "OdaberiVježbe": "Odaberi vježbe",
          "PrilagodiSvojTrening": "Prilagodi svoj trening",
          "OdaberiPozicijeZaVježbanje": "Odaberi pozicije za vježbanje",
          "OdaberiJedanOdPonuđenihAvataraKojiTiSeNajvišeSviđa": "Odaberi jedan od ponuđenih avatara koji ti se najviše sviđa",
          "OdaberiAvatar": "Odaberi avatar",
          "MolimTePodijeliSaMnomNekolikoInformacijaKakoBihTeBoljeUpoznala": "Molim te podijeli sa mnom nekoliko informacija kako bih te bolje upoznala",
          "SveInformacijeKojeMiSadaPodijelišMoćiČešKasnijePromijenitiUPostavkama": "Sve informacije koje mi sada podijeliš moći češ kasnije promijeniti u postavkama",
          "KakoSeZoveš": "Kako se zoveš?",
          "appsluzi": "Aplikacija služi za vježbanje i učenje",
          "PrednjomIStražnjomKameromMožešSnimatiPokretTijela": "Prednjom i stražnjom kamerom možeš snimati pokret tijela",
          "UmjestoVlastitimTijelomMožešVježbatiISKarticama": "Umjesto vlastitim tijelom možeš vježbati i s karticama",
          "GibalicaTiNudi3Igre": "Gibalica ti nudi 3 igre...",
          "IgraSVježbamaZaRukeINoge": "igra s vježbama za ruke i noge",
          "ZabavnaIgraKoncentracije": "zabavna igra koncentracije",
          "IgraPamćenjaRedoslijedaVježbi": "igra pamćenja redoslijeda vježbi",
          "GibalicaPratiTvojNapredakZaSvakuOdIgara": "Gibalica prati tvoj napredak za svaku od igara",
          "Čučanj": "Čučanj",
          "IGRAJ": "IGRAJ",
          "UVis": "U vis",
          "LijevaI": "Lijeva",
          "Desna": "Desna",
          "Ruka": "ruka",
          "Lijeva": "Lijeva",
          "VrstaSlova": "Vrsta slova",
          "VelikaIMalaTiskana": "Velika i mala tiskana",
          "VelikaTiskana": "VELIKA TISKANA",
          "KolikoDugoŽelišVježbati": "Koliko dugo želiš vježbati?",
          "KojiProgramVježbeŽeliš" : "Koji program vježbanja želiš?",
          "OdaberiProgram" : "Odaberi program"
        },
        'en_US': {
          "OpcijePrilagodbi": "Accessibility options",
          "BokJaSam": "Hi, I am",
          "Gibalica": "Gibalica",
          "BrojPonavljanjaVježbe": "Number of repetitions of the exercise",
          "GibalicaGleda": "Gibalica is watching who?",
          "Mene": "ME",
          "Kartice": "CARDS",
          "Igraj": "PLAY",
          "IGRAJ": "PLAY",
          "Trening": "TRAINING",
          "GornjiDioTijela": "Upper body",
          "DonjiDioTijela": "Lower body",
          "Sve": "All",
          "LijevaRuka": "Left hand",
          "DesnaRuka": "Right hand",
          "LijevaIDesnaRuka": "Left and right hand",
          "Noge": "Legs",
          "NogeIČučanj": "Legs and squats",
          "KažeBok": "says hi!",
          "DragoMiTeVidjetiOvdje": "Veselim se našem druženju",
          "DobroDošaola": "kroz vježbu",
          "Kreni": "Go!",
          "Postavke": "SETTINGS",
          "IspisKartica": "Card printing",
          "PromjenaIzgledaAplikacije": "Change the look of the app",
          "SvijetliNačin": "Bright way",
          "TamniNačin": "The dark way",
          "PromjenaVeličineTeksta": "Resize text",
          "Zvuk": "Sound",
          "UpaliZvuk": "On",
          "UgasiZvuk": "Off",
          "PromjenaJezika": "Change language",
          "Hrvatski": "Croatian",
          "Engleski": "English",
          "InformacijeOAplikaciji": "Application information",
          "PonovnoUpoznajAplikaciju": "Meet the app again",
          "Oooops": "Oooops ... :(",
          "KakoBiNastaviolaDaljePotrebnoJeZadovoljitiSljedećeUvjete": "In order to continue, the following conditions must be met:",
          "UpisatiSvojeIme": "- enter your name",
          "OdabratiAvatar": "- select avatar",
          "OdabratiBaremJednuVježbu": "- select at least one exercise",
          "Osobno": "PERSONALLY",
          "Ponavljanje": "Repetition",
          "PONAVLJANJE1": "REPETITION",
          "DesnaNoga": "Right foot",
          "LijevaNoga": "Left foot",
          "KlikniZaViše": "Click for more!",
          "PodatciOVježbanju": "Exercise data",
          "Preskoči": "Skip",
          "UpoznajmoSe": "Let's meet!",
          "SadaKadaZnašŠtoTeSveČekaMožemoKrenuti": "Now that you know what awaits you, we can move on",
          "DanINoć": "DAY and NIGHT",
          "GibajSe": "Move!",
          "SuperSadaJeSveSpremno": "Great, now everything is ready!",
          "LijevaUVis": "Left up",
          "DesnaUVis": "Right up",
          "SaStrane": "On the side",
          "UVisISaStrane": "Up and to the side",
          "RukeI": "HANDS i",
          "Obje": "BOTH",
          "LijevaIliDesnaUVis": "Left or right up",
          "Raskorak": "Gap",
          "UVisISaStraneIstiPoložaj": "Up and on the side the same position",
          "UVisISaStraneRazičitiPoložaj": "Up and on the side different positions",
          "OdaberiVježbe": "Choose exercises",
          "PrilagodiSvojTrening": "Adjust your training",
          "OdaberiPozicijeZaVježbanje": "Choose exercise positions",
          "OdaberiJedanOdPonuđenihAvataraKojiTiSeNajvišeSviđa": "Choose one of the offered avatars that you like the most",
          "OdaberiAvatar": "Select an avatar",
          "MolimTePodijeliSaMnomNekolikoInformacijaKakoBihTeBoljeUpoznala": "Please share with me some information to get to know you better",
          "SveInformacijeKojeMiSadaPodijelišMoćiČešKasnijePromijenitiUPostavkama": "You will be able to change all the information you share with me later in the settings",
          "KakoSeZoveš": "What's your name?",
          "appsluzi": "The application is used for practice and learning",
          "PrednjomIStražnjomKameromMožešSnimatiPokretTijela": "You can record body movement with the front and rear cameras",
          "UmjestoVlastitimTijelomMožešVježbatiISKarticama": "Instead of your own body, you can also practice with cards",
          "GibalicaTiNudi3Igre": "Gibalica offers you 3 games ...",
          "IgraSVježbamaZaRukeINoge": "play with arm and leg exercises",
          "ZabavnaIgraKoncentracije": "a fun game of concentration",
          "IgraPamćenjaRedoslijedaVježbi": "a game of memorizing the sequence of exercises",
          "GibalicaPratiTvojNapredakZaSvakuOdIgara": "Gibalica monitors your progress for each of the games",
          "Čučanj": "Squat",
          "UVis": "Up",
          "LijevaI": "Left and",
          "Desna": "Right",
          "Ruka": "hand",
          "Lijeva": "Left",
          "VrstaSlova": "Letter type",
          "VelikaIMalaTiskana": "Uppercase and lowercase",
          "VelikaTiskana": "UPPERCASE",
          "KolikoDugoŽelišVježbati": "How long do you want to exercise?",
          "KojiProgramVježbeŽeliš" : "Which exercise program do you want?",
          "OdaberiProgram" : "Choose program"
        },
        'HR_HR': {
          "OpcijePrilagodbi": "OPCIJE PRILAGODBI",
          "BokJaSam": "BOK, JA SAM",
          "Gibalica": "GIBALICA",
          "BrojPonavljanjaVježbe": "BROJ PONAVLJANJA VJEŽBE",
          "GibalicaGleda": "GIBALICA GLEDA?",
          "Mene": "MENE",
          "Kartice": "KARTICE",
          "Igraj": "IGRAJ",
          "Trening": "TRENING",
          "GornjiDioTijela": "GORNJI DIO TIJELA",
          "DonjiDioTijela": "DONJI DIO TIJELA",
          "Sve": "SVE",
          "LijevaRuka": "LIJEVA RUKA",
          "DesnaRuka": "DESNA RUKA",
          "LijevaIDesnaRuka": "LIJEVA I DESNA RUKA",
          "Noge": "NOGE",
          "NogeIČučanj": "NOGE I ČUČANJ",
          "KažeBok": "KAŽE BOK!",
          "DragoMiTeVidjetiOvdje": "VESELIM SE NAŠEM DRUŽENJU",
          "DobroDošaola": "KROZ VJEŽBU",
          "Kreni": "KRENI!",
          "Postavke": "POSTAVKE",
          "IspisKartica": "ISPIS KARTICA",
          "PromjenaIzgledaAplikacije": "PROMJENA IZGLEDA APLIKACIJE",
          "SvijetliNačin": "SVIJETLI NAČIN",
          "TamniNačin": "TAMNI NAČIN",
          "PromjenaVeličineTeksta": "PROMJENA VELIČINE TEKSTA",
          "Zvuk": "ZVUK",
          "UpaliZvuk": "UKLJUČI",
          "UgasiZvuk": "ISKLJUČI",
          "PromjenaJezika": "PROMJENA JEZIKA",
          "Hrvatski": "HRVATSKI",
          "Engleski": "ENGLESKI",
          "InformacijeOAplikaciji": "INFORMACIJE O APLIKACIJI",
          "PonovnoUpoznajAplikaciju": "PONOVNO UPOZNAJ APLIKACIJU",
          "Oooops": "OOOOPS... :(",
          "KakoBiNastaviolaDaljePotrebnoJeZadovoljitiSljedećeUvjete": "KAKO BI NASTAVIO/LA DALJE POTREBNO JE ZADOVOLJITI SLJEDEĆE UVJETE:",
          "UpisatiSvojeIme": " - UPISATI SVOJE IME",
          "OdabratiAvatar": " - ODABRATI AVATAR",
          "OdabratiBaremJednuVježbu": " - ODABRATI BAREM JEDNU VJEŽBU",
          "Osobno": "OSOBNO",
          "Ponavljanje": "PONAVLJANJE",
          "PONAVLJANJE1": "PONAVLJANJE",
          "DesnaNoga": "DESNA NOGA",
          "LijevaNoga": "LIJEVA NOGA",
          "KlikniZaViše": "KLIKNI ZA VIŠE!",
          "PodatciOVježbanju": "PODATCI O VJEŽBANJU",
          "Preskoči": "PRESKOČI",
          "UpoznajmoSe": "UPOZNAJMO SE!",
          "SadaKadaZnašŠtoTeSveČekaMožemoKrenuti": "SADA KADA ZNAŠ ŠTO TE SVE ČEKA, MOŽEMO KRENUTI",
          "DanINoć": "DAN I NOĆ",
          "GibajSe": "GIBAJ SE!",
          "SuperSadaJeSveSpremno": "SUPER, SADA JE SVE SPREMNO!",
          "LijevaUVis": "LIJEVA U VIS",
          "DesnaUVis": "DESNA U VIS",
          "SaStrane": "SA STRANE",
          "UVisISaStrane": "U VIS I SA STRANE",
          "RukeI": "RUKE I",
          "Obje": "OBJE",
          "LijevaIliDesnaUVis": "LIJEVA ILI DESNA U VIS",
          "Raskorak": "RASKORAK",
          "UVisISaStraneIstiPoložaj": "U VIS I SA STRANE ISTI POLOŽAJ",
          "UVisISaStraneRazičitiPoložaj": "U VIS I SA STRANE RAZIČITI POLOŽAJ",
          "OdaberiVježbe": "ODABERI VJEŽBE",
          "PrilagodiSvojTrening": "PRILAGODI SVOJ TRENING",
          "OdaberiPozicijeZaVježbanje": "ODABERI POZICIJE ZA VJEŽBANJE",
          "OdaberiJedanOdPonuđenihAvataraKojiTiSeNajvišeSviđa": "ODABERI JEDAN OD PONUĐENIH AVATARA KOJI TI SE NAJVIŠE SVIĐA",
          "OdaberiAvatar": "ODABERI AVATAR",
          "MolimTePodijeliSaMnomNekolikoInformacijaKakoBihTeBoljeUpoznala": "MOLIM TE PODIJELI SA MNOM NEKOLIKO INFORMACIJA KAKO BIH TE BOLJE UPOZNALA",
          "SveInformacijeKojeMiSadaPodijelišMoćiČešKasnijePromijenitiUPostavkama": "SVE INFORMACIJE KOJE MI SADA PODIJELIŠ MOĆI ČEŠ KASNIJE PROMIJENITI U POSTAVKAMA",
          "KakoSeZoveš": "KAKO SE ZOVEŠ?",
          "appsluzi": "APLIKACIJA SLUŽI ZA VJEŽBANJE I UČENJE",
          "PrednjomIStražnjomKameromMožešSnimatiPokretTijela": "PREDNJOM I STRAŽNJOM KAMEROM MOŽEŠ SNIMATI POKRET TIJELA",
          "UmjestoVlastitimTijelomMožešVježbatiISKarticama": "UMJESTO VLASTITIM TIJELOM MOŽEŠ VJEŽBATI I S KARTICAMA",
          "GibalicaTiNudi3Igre": "GIBALICA TI NUDI 3 IGRE...",
          "IgraSVježbamaZaRukeINoge": "IGRA S VJEŽBAMA ZA RUKE I NOGE",
          "ZabavnaIgraKoncentracije": "ZABAVNA IGRA KONCENTRACIJE",
          "IgraPamćenjaRedoslijedaVježbi": "IGRA PAMĆENJA REDOSLIJEDA VJEŽBI",
          "GibalicaPratiTvojNapredakZaSvakuOdIgara": "GIBALICA PRATI TVOJ NAPREDAK ZA SVAKU OD IGARA",
          "Čučanj": "ČUČANJ",
          "IGRAJ": "IGRAJ",
          "UVis": "U VIS",
          "LijevaI": "LIJEVA",
          "Desna": "DESNA",
          "Ruka": "RUKA",
          "Lijeva": "LIJEVA",
          "VrstaSlova": "VRSTA SLOVA",
          "VelikaIMalaTiskana": "Velika i mala tiskana",
          "VelikaTiskana": "VELIKA TISKANA",
          "KolikoDugoŽelišVježbati": "KOLIKO DUGO ŽELIŠ VJEŽBATI?",
          "KojiProgramVježbeŽeliš" : "KOJI PROGRAM VJEŽBANJA ŽELIŠ?",
          "OdaberiProgram" : "ODABERI PROGRAM"
        },
        'EN_US': {
          "OpcijePrilagodbi": "ACCESSIBILITY OPTIONS",
          "BokJaSam": "HI, I AM",
          "Gibalica": "GIBALICA",
          "BrojPonavljanjaVježbe": "NUMBER OF REPETITIONS OF THE EXERCISE",
          "GibalicaGleda": "GIBALICA IS WATCHING WHO?",
          "Mene": "ME",
          "Kartice": "CARDS",
          "Igraj": "PLAY",
          "IGRAJ": "PLAY",
          "Trening": "TRAINING",
          "GornjiDioTijela": "UPPER BODY",
          "DonjiDioTijela": "LOWER BODY",
          "Sve": "ALL",
          "LijevaRuka": "LEFT HAND",
          "DesnaRuka": "RIGHT HAND",
          "LijevaIDesnaRuka": "LEFT AND RIGHT HAND",
          "Noge": "LEGS",
          "NogeIČučanj": "LEGS AND SQUATS",
          "KažeBok": "SAYS HI!",
          "DragoMiTeVidjetiOvdje": "NICE TO SEE YOU HERE ...",
          "DobroDošaola": "WELCOME!",
          "Kreni": "GO!",
          "Postavke": "SETTINGS",
          "IspisKartica": "CARD PRINTING",
          "PromjenaIzgledaAplikacije": "CHANGE THE LOOK OF THE APP",
          "SvijetliNačin": "BRIGHT WAY",
          "TamniNačin": "THE DARK WAY",
          "PromjenaVeličineTeksta": "RESIZE TEXT",
          "Zvuk": "SOUND",
          "UpaliZvuk": "ON",
          "UgasiZvuk": "OFF",
          "PromjenaJezika": "CHANGE LANGUAGE",
          "Hrvatski": "CROATIAN",
          "Engleski": "ENGLISH",
          "InformacijeOAplikaciji": "APPLICATION INFORMATION",
          "PonovnoUpoznajAplikaciju": "MEET THE APP AGAIN",
          "Oooops": "OOOOPS ... :(",
          "KakoBiNastaviolaDaljePotrebnoJeZadovoljitiSljedećeUvjete": "IN ORDER TO CONTINUE, THE FOLLOWING CONDITIONS MUST BE MET:",
          "UpisatiSvojeIme": "- ENTER YOUR NAME",
          "OdabratiAvatar": "- SELECT AVATAR",
          "OdabratiBaremJednuVježbu": "- SELECT AT LEAST ONE EXERCISE",
          "Osobno": "PERSONALLY",
          "Ponavljanje": "REPETITION",
          "PONAVLJANJE1": "REPETITION",
          "DesnaNoga": "RIGHT FOOT",
          "LijevaNoga": "LEFT FOOT",
          "KlikniZaViše": "CLICK FOR MORE!",
          "PodatciOVježbanju": "EXERCISE DATA",
          "Preskoči": "SKIP",
          "UpoznajmoSe": "LET'S MEET!",
          "SadaKadaZnašŠtoTeSveČekaMožemoKrenuti": "NOW THAT YOU KNOW WHAT AWAITS YOU, WE CAN MOVE ON",
          "DanINoć": "DAY AND NIGHT",
          "GibajSe": "MOVE!",
          "SuperSadaJeSveSpremno": "GREAT, NOW EVERYTHING IS READY!",
          "LijevaUVis": "LEFT UP",
          "DesnaUVis": "RIGHT UP",
          "SaStrane": "ON THE SIDE",
          "UVisISaStrane": "UP AND TO THE SIDE",
          "RukeI": "HANDS I",
          "Obje": "BOTH",
          "LijevaIliDesnaUVis": "LEFT OR RIGHT UP",
          "Raskorak": "GAP",
          "UVisISaStraneIstiPoložaj": "UP AND ON THE SIDE THE SAME POSITION",
          "UVisISaStraneRazičitiPoložaj": "UP AND ON THE SIDE DIFFERENT POSITIONS",
          "OdaberiVježbe": "CHOOSE EXERCISES",
          "PrilagodiSvojTrening": "ADJUST YOUR TRAINING",
          "OdaberiPozicijeZaVježbanje": "CHOOSE EXERCISE POSITIONS",
          "OdaberiJedanOdPonuđenihAvataraKojiTiSeNajvišeSviđa": "CHOOSE ONE OF THE OFFERED AVATARS THAT YOU LIKE THE MOST",
          "OdaberiAvatar": "SELECT AN AVATAR",
          "MolimTePodijeliSaMnomNekolikoInformacijaKakoBihTeBoljeUpoznala": "PLEASE SHARE WITH ME SOME INFORMATION TO GET TO KNOW YOU BETTER",
          "SveInformacijeKojeMiSadaPodijelišMoćiČešKasnijePromijenitiUPostavkama": "YOU WILL BE ABLE TO CHANGE ALL THE INFORMATION YOU SHARE WITH ME LATER IN THE SETTINGS",
          "KakoSeZoveš": "WHAT'S YOUR NAME?",
          "appsluzi": "THE APPLICATION IS USED FOR PRACTICE AND LEARNING",
          "PrednjomIStražnjomKameromMožešSnimatiPokretTijela": "YOU CAN RECORD BODY MOVEMENT WITH THE FRONT AND REAR CAMERAS",
          "UmjestoVlastitimTijelomMožešVježbatiISKarticama": "INSTEAD OF YOUR OWN BODY, YOU CAN ALSO PRACTICE WITH CARDS",
          "GibalicaTiNudi3Igre": "GIBALICA OFFERS YOU 3 GAMES ...",
          "IgraSVježbamaZaRukeINoge": "PLAY WITH ARM AND LEG EXERCISES",
          "ZabavnaIgraKoncentracije": "A FUN GAME OF CONCENTRATION",
          "IgraPamćenjaRedoslijedaVježbi": "A GAME OF MEMORIZING THE SEQUENCE OF EXERCISES",
          "GibalicaPratiTvojNapredakZaSvakuOdIgara": "GIBALICA MONITORS YOUR PROGRESS FOR EACH OF THE GAMES",
          "Čučanj": "SQUAT",
          "UVis": "UP",
          "LijevaI": "LEFT AND",
          "Desna": "RIGHT",
          "Ruka": "HAND",
          "Lijeva": "LEFT",
          "VrstaSlova": "LETTER TYPE",
          "VelikaIMalaTiskana": "Uppercase and lowercase",
          "VelikaTiskana": "UPPERCASE",
          "KolikoDugoŽelišVježbati": "HOW LONG DO YOU WANT TO EXERCISE?",
          "KojiProgramVježbeŽeliš" : "WHICH EXERCISE PROGRAM DO YOU WANT?",
          "OdaberiProgram" : "CHOOSE PROGRAM"
        },
      };
}
