Map<String, String> TrainingTitleEnglish = {
  'Lijeva i desna ruka - u vis': "Left and right arm - Up",
  'Lijeva i desna ruka - sa strane': "Left and right arm - On the side",
  'Lijeva i desna ruka - u vis i sa strane isti položaj': "Left and right arm - Up and to the side same position",
  'Lijeva i desna ruka - u vis i sa strane razičiti položaj': "Left and right arm - Up and on the side different positions",
  'Lijeva i desna ruka - sve': "Left and right arm - All",
  'Lijeva i desna noga - u vis': "Left and right leg - Up",
  'Raskorak': "Gap",
  'Čučanj': 'Squat',
  'Sve': 'Everything',
  'Lijeva ruka - u vis': 'Left arm - Up',
  'Lijeva ruka - sa strane': 'Left arm - On the side',
  'Lijeva ruka - u vis i sa strane': 'Left arm - Up and on the side',
  'Desna ruka - u vis': 'Right arm - Up',
  'Desna ruka - sa strane': 'Right arm - On the side',
  'Desna ruka - u vis i sa strane': 'Right arm - Up and on the side',
  'Lijeva noga - u vis': 'Left leg - Up',
  'Desna noga - u vis': 'Right leg - Up',
};
